################
#
# LockLogin manager module
# by: KarmaDev ( Official plugin
# module )
#

#Help message header
HelpHeader:
  - "&5&m----------&r&e LockLogin modules commands &5&m-----------"
  - " "

#Help message footer
HelpFooter:
  - "&5&m---------------------&r &7{page}&5/&7{pages} &5&m---------------------"

#Help message format
HelpFormat:
  - "&7{command} &5&m--"
  - "&d{description}"
  - " "